"""add User.create_at

Revision ID: d0838596d254
Revises: f8b0edcb33be
Create Date: 2024-12-01 16:51:36.772507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0838596d254'
down_revision: Union[str, None] = 'f8b0edcb33be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
